[package]
name = "CREPLrs"
version = "0.1.0"
edition = "2024"
links = "ffi"

[dependencies]
chumsky = "0.12.0"
libc = "0.2.180"
logos = "0.16.1"
once_cell = "1.21.3"
pkg-config = "0.3.32"
rustyline = "17.0.2"
# libffi-sys = "4.1.0"

[build-dependencies]
pkg-config = "0.3.32"
