[package]
name = "CREPLrs"
version = "0.1.0"
edition = "2024"
links = "ffi"

[dependencies]
libc = "0.2.180"
logos = "0.16.1"
pkg-config = "0.3.32"
# libffi-sys = "4.1.0"

[build-dependencies]
pkg-config = "0.3.32"
